apiVersion: apps/v1
kind: Deployment
metadata:
  name: pradeep-deploy-1
  labels:
    app: nani
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nani
  template:
    metadata:
      labels:
        app: nani
    spec:
      containers:
        - name: pradeep-container-1
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pradeep-service-1
spec:
  type: NodePort
  selector:
    app: nani
  ports:
    - port: 80
      targetPort: 80
