apiVersion: apps/v1
kind: Deployment
metadata:
  name: nani-deploy
  labels:
    app: bank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: nani-container
          image: ubuntu
          ports:
            - containerPort: 8080
