apiVersion: apps/v1
kind: Deployment
metadata:
  name: nani-deploy
  labels:
    app: bank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: nani-container
          image: ubuntu
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nani-service
spec:
  type: NodePort
  selector:
    app: bank
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30710
