apiVersion: apps/v1
kind: Deployment
metadata:
  name: msd
  labels:
    app: seven
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seven
  template:
    metadata:
      labels:
        app: seven
    spec:
      containers:
        - name: seven-container
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: iris
spec:
  type: LoadBalancer
  selector:
    app: seven
  ports:
    - port: 80
      targetPort: 80
