apiVersion: apps/v1
kind: Deployment
metadata:
  name: pradeep-deploy
  labels:
    app: nani
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nani
  template:
    metadata:
      labels:
        app: nani
    spec:
      containers:
        - name: pradeep-container
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pradeep-service
spec:
  type: NodePort
  selector:
    app: nani
  ports:
    - port: 80
      targetPort: 80
